language: csharp
solution: ORM.sln
install:
- nuget restore ORM.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release ORM.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ORM.UnitTests/bin/Release/ORM.UnitTests.dll