language: csharp
solution: ORM.sln
install:
- nuget restore ORM.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release ORM.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ORM.UnitTests/bin/Release/ORM.UnitTests.dll
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: mSAWBAOrWTPv9qTh2D/y7dbOWeAMWiW/XY410Plr3DuE2TC2F8ey7WTEB96kV7+YkshljG0U0Gy9mddDrh9OhORyH+R/amFC4jm+PPIP3JE6HLeTU0mZe76WNweYzHLwioN3DLuaaR8XMhejJC0ya80CTT8AgYhhRtd+X5pV/vnsYGvWrl5NZaVhgx+Ln3fE72TlRj3mxYLoWPwnJafTootq45o/k3AcNb79mOk3qRDzIQpMych41Q5rbvS66XU5dx4oqmryb/BeXfqS6svZPn6CpmcpKlgQojONypmaCpkEhhIlgWYhK8eoIfvuCqPmqW0S2WH4qC193rwYoxQkDNiZBoNM33hw8G5W2ail8LDhCwlHvk2LTy3VaDtDe4lj1ECQ/ZG2EWJPQPpRJoKjM3QIY54+z22iscXs8lERtTx/34pEhKfi2or5hAIU4N2HVyhKPu0fkodGylPExBhhOYe7RHfM9r62mYFmtyzQSj1pQ4j2kkYQPOiUkEORBKkfPIc+iPe74pRUrZJ/9aQoQ2MMjLvg0MnuRLXKlijt13ArHnwo7zSEWEOTPuxat2MMVRxyqUbMKo2cjVPDuilr/SWjTafADu0gVxebL2pvPcEPJIGje8KyHXMYuglR9JeJjuu1KyO2ws5+HMymjfOElOnck5JWwycEIgWRT9R2C6Y=
  file: 'ORM/bin/Release/ORM.dll'
  on:
    repo: thabart/SimpleOrm
    branch: release
