before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
after_build:
  - 7z a ORM.zip %APPVEYOR_BUILD_FOLDER%\ORM\bin\%CONFIGURATION%\*.dll
configuration: Release
deploy:
  - provider: GitHub
    auth_token:
     secure: LEpRiorEnE0JEQ3AfQytlf3dBQ8rNYG/QWkbuzlTq20NhZQG91/o/sCp5er5JPdY