version: 1.0.{build}
configuration: Release
platform: Any CPU
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
- appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
- nuget-restore
build:
  verbosity: minimal
after_build:
- nuget pack SimpleOrm.nuspec -Prop Configuration=%CONFIGURATION% -Prop version=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: ORM\bin\$(configuration)
  name: ORM
- path: SimpleOrm.*.nupkg
  name: Nuget
- path: ORM.VSPackage\bin\$(configuration)
  name: VSPackage
deploy:
after_deploy:
  - ps: Vsix-PublishToGallery ORM.VSPackage\bin\$env:APPVEYOR_BUILD_VERSION\*.vsix